name: CI/CD

on: [push]

jobs:
  codestyle-tests:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'NO_CI')"
    steps:
    - name: Checkout Repository
      uses: actions/checkout@master
      with:
        fetch-depth: 1
    - name: Checkout Build Repository
      uses: actions/checkout@master
      with:
          fetch-depth: 1
          ref: develop
          repository: Karaka/Build
          path: Build
    - name: Install NPM
      uses: actions/setup-node@v3
      with:
        node-version: '14'
        cache: 'npm'
    - run: npm install
    - name: eslint
      run: npx eslint ./ -c Build/Config/.eslintrc.json
